### ISSUE TITLE
Prepare Flight Screen UI

### ISSUE THREAD

**Issue by kkaigle** [opensky-to/client#81]
The prepare flight plan screen lacks enough margin for scrolling the main page. With the amount of smaller scroll elements taking up the space, its hard to find a spot on the screen to scroll the window down to view those other elements towards the bottom of the screen.

**Comment by sushiat** [comment]
If possible please attach a screenshot

**Comment by kkaigle** [comment]
![image](https://github.com/opensky-to/client/assets/83706649/0472f47c-0a49-4357-8c45-2c7b5ea9f6c2)
![image](https://github.com/opensky-to/client/assets/83706649/89312d22-f42f-4507-a0e4-6625fffee2a6)

**Comment by kkaigle** [comment]
First image is 1440, second is 1080 after dragging the window over

**Comment by kkaigle** [comment]
![image](https://github.com/opensky-to/client/assets/83706649/501b688a-97a3-477b-9c8a-a8f97247c063)

in order to scroll down, you need to be between the boxes within the screen, otherwise you end up scrolling the map or the OFP box when you over over them

**Comment by sushiat** [comment]
Not quite sure how to prevent this though as controls like the map capture mouse wheel events. Unless you say we should disable zooming for that map, not quite sure.
