### ISSUE TITLE
Client crash when renewing auth token

### ISSUE THREAD

**Issue by kkaigle** [opensky-to/client#85]
Log attached
[client_crash.log](https://github.com/opensky-to/client/files/13459430/client_crash.log)

**Comment by sushiat** [comment]
Looked at this one, looks more like a bug in the library that contains the left navigation view control. All I'm doing is clearing it and then adding the elements your roles grant you. Will park this for now - leave it open and all and see if it happens again. Then we might have to open this as an issue with the developer of it. If it's a one time thing we can maybe write it off as a glitch. But do let me know.
