### ISSUE TITLE
Charts overlap in finances

### ISSUE THREAD

**Issue by kkaigle** [opensky-to/client#91]
![image](https://github.com/opensky-to/client/assets/83706649/94e0cbfb-fc2c-41f1-bafe-06f2f23975cb)

**Comment by sushiat** [comment]
Guess the easiest and maybe user friendly solution would be some kind of auto shortener to most significant "unit":

840162480 => 840.2m .... 162480 => 162.5k ... etc.

**Comment by kkaigle** [comment]
Yea, in which case a .csv export would be useful

**Comment by sushiat** [comment]
![image](https://github.com/opensky-to/client/assets/6118673/7f9aacdc-65f5-40b7-9bf2-678b987fdbc9)

Implemented, will be in next update. The CSV export would
a) be a separate issue, please don't mix them
b) not quite so easy, as the main grid has sub-grids (flights have child records)
